### ISSUE TITLE
Multiple UX issues

### ISSUE THREAD

**Issue by peanutbutterclassic** [peanutbutterclassic/insync#1]
# User Story:
As a user, **I can** navigate the website (quiz) with ease using the easy-to-find buttons **to get** to the intended page/content quickly. 

# Acceptance Criteria:
1. Buttons include links to navigate to other pages.
2. The user can start the quiz by selecting START QUIZ to proceed.
3. The user can return to the main page by selecting the RETURN button.
4. The user can view the leaderboard page by selecting the LEADERBOARD button.
5. The user can save the score by selecting the SAVE SCORE button.

# Tasks:
- [ ] Create buttons on the homepage for START QUIZ, LEADERBOARD.
- [ ] Create a button on the homepage for START QUIZ.
- [ ] Create a button on the homepage for LEADERBOARD to view the score.
- [ ] Create a button on the quiz page for SAVE SCORE quiz session finishes.
- [ ] Create a button on the leaderboard for RETURN to the homepage.

**Comment by peanutbutterclassic** [comment]
I know I am done when:
1. Buttons include links to navigate to other pages.
2. The user can start the quiz by selecting START QUIZ to proceed.
3. The user can return to the main page by selecting the RETURN button.
4. The user can view the leaderboard page by selecting the LEADERBOARD button.
5. The user can save the score by selecting the SAVE SCORE button.
