### ISSUE TITLE
USER STORY:  CSS file

### ISSUE THREAD

**Issue by peanutbutterclassic** [peanutbutterclassic/insync#3]
As a **user**, I can **see the site is well designed with good CSS** so that **it is easy to use and appealing**

# Acceptance Criteria:
- CSS is updated and added to the website 

# Tasks:
- [ ] Add CSS to repository
- [ ] Check CSS works correctly
- [ ] Verify compatibility with all devices
